name: nemr_portfolio
description: Omar Elnemr's Portfolio including Experience, Projects and Contact Form.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.5
  dashed_line: ^0.1.0+3
  emailjs: ^1.1.0
  flutter:
    sdk: flutter

  flutter_animate: ^4.1.1+1
  flutter_hooks: ^0.18.6
  get_storage: ^2.1.1
  hooks_riverpod: ^2.3.0
  http: ^0.13.5
  rive: ^0.10.2
  seo: ^0.0.4
  url_launcher: ^6.1.10

flutter_icons:
  image_path: "icon/logo.png"
  web:
    generate: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0


flutter:

  uses-material-design: false
  assets:
    - assets/icons/
    - assets/rive/
    - html/
  fonts:
    - family: Roboto Mono
      fonts:
        - asset: fonts/RobotoMono.ttf
        - asset: fonts/RobotoMono-Italic.ttf

    - family: VT323
      fonts:
        - asset: fonts/VT323.ttf
          weight: 700
